# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hungrygames.ui'
#
# Created: Sat Oct 19 07:23:39 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_HungryGames(object):
    def setupUi(self, HungryGames):
        HungryGames.setObjectName(_fromUtf8("HungryGames"))
        HungryGames.resize(777, 540)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(HungryGames.sizePolicy().hasHeightForWidth())
        HungryGames.setSizePolicy(sizePolicy)
        HungryGames.setMinimumSize(QtCore.QSize(777, 540))
        HungryGames.setMaximumSize(QtCore.QSize(777, 540))
        HungryGames.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(HungryGames)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gamebox = QtGui.QGroupBox(self.centralwidget)
        self.gamebox.setGeometry(QtCore.QRect(10, 10, 751, 281))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.gamebox.setFont(font)
        self.gamebox.setObjectName(_fromUtf8("gamebox"))
        self.Game1 = QtGui.QTableView(self.gamebox)
        self.Game1.setGeometry(QtCore.QRect(60, 70, 161, 161))
        self.Game1.setObjectName(_fromUtf8("Game1"))
        self.prisonersdillema = QtGui.QRadioButton(self.gamebox)
        self.prisonersdillema.setGeometry(QtCore.QRect(70, 240, 141, 21))
        self.prisonersdillema.setChecked(True)
        self.prisonersdillema.setObjectName(_fromUtf8("prisonersdillema"))
        self.chicken = QtGui.QRadioButton(self.gamebox)
        self.chicken.setGeometry(QtCore.QRect(350, 240, 81, 21))
        self.chicken.setObjectName(_fromUtf8("chicken"))
        self.staghunt = QtGui.QRadioButton(self.gamebox)
        self.staghunt.setGeometry(QtCore.QRect(590, 240, 91, 21))
        self.staghunt.setObjectName(_fromUtf8("staghunt"))
        self.line = QtGui.QFrame(self.gamebox)
        self.line.setGeometry(QtCore.QRect(60, 140, 161, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_3 = QtGui.QFrame(self.gamebox)
        self.line_3.setGeometry(QtCore.QRect(130, 70, 20, 161))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.label = QtGui.QLabel(self.gamebox)
        self.label.setGeometry(QtCore.QRect(70, 90, 62, 41))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_5 = QtGui.QLabel(self.gamebox)
        self.label_5.setGeometry(QtCore.QRect(70, 170, 62, 41))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.gamebox)
        self.label_6.setGeometry(QtCore.QRect(150, 90, 62, 41))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.gamebox)
        self.label_7.setGeometry(QtCore.QRect(150, 170, 62, 41))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_2 = QtGui.QLabel(self.gamebox)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 41, 41))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.gamebox)
        self.label_3.setGeometry(QtCore.QRect(160, 20, 41, 41))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.gamebox)
        self.label_4.setGeometry(QtCore.QRect(10, 170, 41, 41))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_8 = QtGui.QLabel(self.gamebox)
        self.label_8.setGeometry(QtCore.QRect(80, 20, 41, 41))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.gamebox)
        self.label_9.setGeometry(QtCore.QRect(400, 20, 41, 41))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.gamebox)
        self.label_10.setGeometry(QtCore.QRect(310, 90, 62, 41))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.gamebox)
        self.label_11.setGeometry(QtCore.QRect(390, 90, 62, 41))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.gamebox)
        self.label_12.setGeometry(QtCore.QRect(310, 170, 62, 41))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.gamebox)
        self.label_13.setGeometry(QtCore.QRect(390, 170, 62, 41))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.Game1_2 = QtGui.QTableView(self.gamebox)
        self.Game1_2.setGeometry(QtCore.QRect(300, 70, 161, 161))
        self.Game1_2.setObjectName(_fromUtf8("Game1_2"))
        self.line_4 = QtGui.QFrame(self.gamebox)
        self.line_4.setGeometry(QtCore.QRect(300, 140, 161, 20))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.line_5 = QtGui.QFrame(self.gamebox)
        self.line_5.setGeometry(QtCore.QRect(370, 70, 20, 161))
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.label_14 = QtGui.QLabel(self.gamebox)
        self.label_14.setGeometry(QtCore.QRect(250, 90, 41, 41))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.gamebox)
        self.label_15.setGeometry(QtCore.QRect(250, 170, 41, 41))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.gamebox)
        self.label_16.setGeometry(QtCore.QRect(320, 20, 41, 41))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.gamebox)
        self.label_17.setGeometry(QtCore.QRect(650, 20, 41, 41))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.gamebox)
        self.label_18.setGeometry(QtCore.QRect(560, 90, 62, 41))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.gamebox)
        self.label_19.setGeometry(QtCore.QRect(640, 90, 62, 41))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.gamebox)
        self.label_20.setGeometry(QtCore.QRect(560, 170, 62, 41))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.gamebox)
        self.label_21.setGeometry(QtCore.QRect(640, 170, 62, 41))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.Game1_3 = QtGui.QTableView(self.gamebox)
        self.Game1_3.setGeometry(QtCore.QRect(550, 70, 161, 161))
        self.Game1_3.setObjectName(_fromUtf8("Game1_3"))
        self.line_6 = QtGui.QFrame(self.gamebox)
        self.line_6.setGeometry(QtCore.QRect(550, 140, 161, 20))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.line_7 = QtGui.QFrame(self.gamebox)
        self.line_7.setGeometry(QtCore.QRect(620, 70, 20, 161))
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.label_22 = QtGui.QLabel(self.gamebox)
        self.label_22.setGeometry(QtCore.QRect(500, 90, 41, 41))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.gamebox)
        self.label_23.setGeometry(QtCore.QRect(500, 170, 41, 41))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.gamebox)
        self.label_24.setGeometry(QtCore.QRect(570, 20, 41, 41))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(self.gamebox)
        self.label_25.setGeometry(QtCore.QRect(310, 90, 62, 41))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.gamebox)
        self.label_26.setGeometry(QtCore.QRect(390, 90, 62, 41))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(self.gamebox)
        self.label_27.setGeometry(QtCore.QRect(310, 170, 62, 41))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtGui.QLabel(self.gamebox)
        self.label_28.setGeometry(QtCore.QRect(390, 170, 62, 41))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtGui.QLabel(self.gamebox)
        self.label_29.setGeometry(QtCore.QRect(560, 90, 62, 41))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(self.gamebox)
        self.label_30.setGeometry(QtCore.QRect(640, 90, 62, 41))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_31 = QtGui.QLabel(self.gamebox)
        self.label_31.setGeometry(QtCore.QRect(560, 170, 62, 41))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_32 = QtGui.QLabel(self.gamebox)
        self.label_32.setGeometry(QtCore.QRect(640, 170, 62, 41))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(380, 420, 381, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.startbutton = QtGui.QToolButton(self.centralwidget)
        self.startbutton.setGeometry(QtCore.QRect(520, 460, 111, 31))
        self.startbutton.setObjectName(_fromUtf8("startbutton"))
        self.strategybox = QtGui.QGroupBox(self.centralwidget)
        self.strategybox.setGeometry(QtCore.QRect(10, 300, 351, 191))
        self.strategybox.setObjectName(_fromUtf8("strategybox"))
        self.line_2 = QtGui.QFrame(self.strategybox)
        self.line_2.setGeometry(QtCore.QRect(150, 70, 20, 101))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.referee = QtGui.QCheckBox(self.strategybox)
        self.referee.setGeometry(QtCore.QRect(90, 30, 161, 20))
        self.referee.setChecked(False)
        self.referee.setObjectName(_fromUtf8("referee"))
        self.alwayscooperate = QtGui.QCheckBox(self.strategybox)
        self.alwayscooperate.setGeometry(QtCore.QRect(180, 67, 138, 20))
        self.alwayscooperate.setObjectName(_fromUtf8("alwayscooperate"))
        self.siri = QtGui.QCheckBox(self.strategybox)
        self.siri.setGeometry(QtCore.QRect(180, 151, 87, 20))
        self.siri.setObjectName(_fromUtf8("siri"))
        self.maximin = QtGui.QCheckBox(self.strategybox)
        self.maximin.setGeometry(QtCore.QRect(180, 95, 80, 20))
        self.maximin.setObjectName(_fromUtf8("maximin"))
        self.winstayloseshift = QtGui.QCheckBox(self.strategybox)
        self.winstayloseshift.setGeometry(QtCore.QRect(180, 123, 155, 20))
        self.winstayloseshift.setObjectName(_fromUtf8("winstayloseshift"))
        self.titfortat = QtGui.QCheckBox(self.strategybox)
        self.titfortat.setGeometry(QtCore.QRect(20, 67, 98, 20))
        self.titfortat.setObjectName(_fromUtf8("titfortat"))
        self.alwaysdefect = QtGui.QCheckBox(self.strategybox)
        self.alwaysdefect.setGeometry(QtCore.QRect(20, 151, 113, 20))
        self.alwaysdefect.setObjectName(_fromUtf8("alwaysdefect"))
        self.titfor2tats = QtGui.QCheckBox(self.strategybox)
        self.titfor2tats.setGeometry(QtCore.QRect(20, 95, 120, 20))
        self.titfor2tats.setObjectName(_fromUtf8("titfor2tats"))
        self.random = QtGui.QCheckBox(self.strategybox)
        self.random.setGeometry(QtCore.QRect(20, 123, 77, 20))
        self.random.setObjectName(_fromUtf8("random"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(380, 300, 381, 91))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.roundsqty = QtGui.QLCDNumber(self.groupBox)
        self.roundsqty.setGeometry(QtCore.QRect(300, 30, 64, 41))
        self.roundsqty.setAutoFillBackground(True)
        self.roundsqty.setFrameShape(QtGui.QFrame.Box)
        self.roundsqty.setFrameShadow(QtGui.QFrame.Raised)
        self.roundsqty.setSmallDecimalPoint(False)
        self.roundsqty.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.roundsqty.setProperty("value", 1.0)
        self.roundsqty.setObjectName(_fromUtf8("roundsqty"))
        self.horizontalSlider = QtGui.QSlider(self.groupBox)
        self.horizontalSlider.setGeometry(QtCore.QRect(30, 40, 261, 22))
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(1000)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        HungryGames.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(HungryGames)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 777, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        HungryGames.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(HungryGames)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        HungryGames.setStatusBar(self.statusbar)

        self.retranslateUi(HungryGames)
        QtCore.QObject.connect(self.referee, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.titfortat.setChecked)
        QtCore.QObject.connect(self.referee, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.titfor2tats.setChecked)
        QtCore.QObject.connect(self.referee, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.random.setChecked)
        QtCore.QObject.connect(self.referee, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.alwaysdefect.setChecked)
        QtCore.QObject.connect(self.referee, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.alwayscooperate.setChecked)
        QtCore.QObject.connect(self.referee, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.maximin.setChecked)
        QtCore.QObject.connect(self.referee, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.winstayloseshift.setChecked)
        QtCore.QObject.connect(self.horizontalSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.roundsqty.display)
        QtCore.QObject.connect(self.referee, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.siri.setChecked)
        QtCore.QMetaObject.connectSlotsByName(HungryGames)

    def retranslateUi(self, HungryGames):
        HungryGames.setWindowTitle(_translate("HungryGames", "Hungrygames", None))
        self.gamebox.setTitle(_translate("HungryGames", "Games", None))
        self.prisonersdillema.setText(_translate("HungryGames", "Prisoner\'s Dilemma", None))
        self.chicken.setText(_translate("HungryGames", "Chicken", None))
        self.staghunt.setText(_translate("HungryGames", "Stag Hunt", None))
        self.label.setText(_translate("HungryGames", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#3a23c3;\">3,3</span></p></body></html>", None))
        self.label_5.setText(_translate("HungryGames", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#3a23c3;\">5,0</span></p></body></html>", None))
        self.label_6.setText(_translate("HungryGames", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#3a23c3;\">0,5</span></p></body></html>", None))
        self.label_7.setText(_translate("HungryGames", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#3a23c3;\">1,1</span></p></body></html>", None))
        self.label_2.setText(_translate("HungryGames", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#3a23c3;\">C</span></p></body></html>", None))
        self.label_3.setText(_translate("HungryGames", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#3a23c3;\">D</span></p></body></html>", None))
        self.label_4.setText(_translate("HungryGames", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#3a23c3;\">D</span></p></body></html>", None))
        self.label_8.setText(_translate("HungryGames", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#3a23c3;\">C</span></p></body></html>", None))
        self.label_9.setText(_translate("HungryGames", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#3a23c3;\">D</span></p></body></html>", None))
        self.label_10.setText(_translate("HungryGames", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#3a23c3;\">3,3</span></p></body></html>", None))
        self.label_11.setText(_translate("HungryGames", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#3a23c3;\">0,5</span></p></body></html>", None))
        self.label_12.setText(_translate("HungryGames", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#3a23c3;\">1,1</span></p></body></html>", None))
        self.label_13.setText(_translate("HungryGames", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#3a23c3;\">5,0</span></p></body></html>", None))
        self.label_14.setText(_translate("HungryGames", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#3a23c3;\">C</span></p></body></html>", None))
        self.label_15.setText(_translate("HungryGames", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#3a23c3;\">D</span></p></body></html>", None))
        self.label_16.setText(_translate("HungryGames", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#3a23c3;\">C</span></p></body></html>", None))
        self.label_17.setText(_translate("HungryGames", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#3a23c3;\">D</span></p></body></html>", None))
        self.label_18.setText(_translate("HungryGames", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#3a23c3;\">3,3</span></p></body></html>", None))
        self.label_19.setText(_translate("HungryGames", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#3a23c3;\">0,5</span></p></body></html>", None))
        self.label_20.setText(_translate("HungryGames", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#3a23c3;\">1,1</span></p></body></html>", None))
        self.label_21.setText(_translate("HungryGames", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#3a23c3;\">5,0</span></p></body></html>", None))
        self.label_22.setText(_translate("HungryGames", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#3a23c3;\">C</span></p></body></html>", None))
        self.label_23.setText(_translate("HungryGames", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#3a23c3;\">D</span></p></body></html>", None))
        self.label_24.setText(_translate("HungryGames", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#3a23c3;\">C</span></p></body></html>", None))
        self.label_25.setText(_translate("HungryGames", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#3a23c3;\">3,3</span></p></body></html>", None))
        self.label_26.setText(_translate("HungryGames", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#3a23c3;\">4,6</span></p></body></html>", None))
        self.label_27.setText(_translate("HungryGames", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#3a23c3;\">6,4</span></p></body></html>", None))
        self.label_28.setText(_translate("HungryGames", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#3a23c3;\">1,1</span></p></body></html>", None))
        self.label_29.setText(_translate("HungryGames", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#3a23c3;\">4,4</span></p></body></html>", None))
        self.label_30.setText(_translate("HungryGames", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#3a23c3;\">-5,3</span></p></body></html>", None))
        self.label_31.setText(_translate("HungryGames", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#3a23c3;\">3,-5</span></p></body></html>", None))
        self.label_32.setText(_translate("HungryGames", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#3a23c3;\">2,2</span></p></body></html>", None))
        self.startbutton.setText(_translate("HungryGames", "FIGHT", None))
        self.strategybox.setTitle(_translate("HungryGames", "Strategies", None))
        self.referee.setText(_translate("HungryGames", "  Select / Deselect All", None))
        self.alwayscooperate.setText(_translate("HungryGames", "Always Cooperate", None))
        self.siri.setText(_translate("HungryGames", "Siri", None))
        self.maximin.setText(_translate("HungryGames", "Maximin", None))
        self.winstayloseshift.setText(_translate("HungryGames", "Win-Stay, Lose-Shift", None))
        self.titfortat.setText(_translate("HungryGames", "Tit-For-Tat", None))
        self.alwaysdefect.setText(_translate("HungryGames", "Always Defect", None))
        self.titfor2tats.setText(_translate("HungryGames", "Tit-For-2-Tats", None))
        self.random.setText(_translate("HungryGames", "Random", None))
        self.groupBox.setTitle(_translate("HungryGames", "Number of Rounds", None))


